import Link from 'next/link';
import {
  BrainCircuit,
  CalendarDays,
  FileText,
  LogOut,
  Settings,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';

export default function AdminDashboardPage() {
  return (
    <div className="flex min-h-screen w-full flex-col bg-muted/40">
      <header className="sticky top-0 z-30 flex h-14 items-center justify-between gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6 py-2">
         <div className="flex items-center gap-3">
            <CalendarDays className="h-8 w-8 text-primary" />
            <span className="text-2xl font-bold text-primary">
              EduScheduler
            </span>
          </div>
          <div className="flex items-center gap-4">
            <span className="hidden text-sm font-medium text-muted-foreground sm:inline-block">
              Admin
            </span>
            <Button variant="outline" size="icon" asChild>
              <Link href="/admin/login">
                <LogOut className="h-4 w-4" />
                <span className="sr-only">Logout</span>
              </Link>
            </Button>
          </div>
      </header>
      <main className="flex-1 items-start gap-4 p-4 sm:px-6 sm:py-0 md:gap-8">
        <div className="mx-auto grid w-full max-w-6xl gap-6">
          <div className="grid gap-6">
            <Card>
              <CardHeader>
                <CardTitle>AI Schedule Generator</CardTitle>
                <CardDescription>
                  Harness the power of AI to create flawless schedules in seconds. Input your constraints and let our intelligent system handle the rest.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <form className="grid gap-4">
                  <div className="grid gap-2">
                    <Label htmlFor="time-constraints">Time Constraints</Label>
                    <Textarea
                      id="time-constraints"
                      placeholder="e.g., Classes only between 9 AM and 5 PM, Monday to Friday."
                    />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="resource-availability">Resource Availability</Label>
                    <Textarea
                      id="resource-availability"
                      placeholder="e.g., Room 101 available all day, Auditorium available only on Wednesday afternoons."
                    />
                  </div>
                  <div className="grid gap-2">
                    <Label htmlFor="task-priorities">Task/Course Priorities</Label>
                    <Textarea
                      id="task-priorities"
                      placeholder="e.g., 'Calculus 101' is a high priority course. 'Beginner's Yoga' is a low priority."
                    />
                  </div>
                  <Button className="w-fit">
                    <BrainCircuit className="mr-2 h-4 w-4" />
                    Generate Schedule
                  </Button>
                </form>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Generated Schedule</CardTitle>
                <CardDescription>
                  This is the optimal schedule generated by the AI based on your inputs.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="rounded-lg border bg-muted p-4 text-sm">
                  <p className="text-muted-foreground">Your generated schedule will appear here...</p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}
